name: Build

on:
  push:
    branches: [ 'main' ]
    tags-ignore: [ '**' ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ 'main' ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
jobs:
  gradle-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v6

    - name: Build with Gradle
      run: ./gradlew build